### PR TITLE
Feat/docker

### PR DESCRIPTION
**Pull request by audreyeternal**
**Pull request recommendations:**
- [x]  _feature/docker and colab support_
Thanks for contributing!

### CODE REVIEW

**Review by Justin-Sonneck — APPROVED** [review]
Awesome, many thanks!

**Review by Justin-Sonneck — APPROVED** [review]
Awesome, many thanks!

**Comment by jxchen01** [comment]
there are a few small linting errors. After some clean up, it is ready to merge

**Comment by Justin-Sonneck** [comment]
Since the linting errors are not related to Yu's docker part, I will fix them for the PR from resubmission to main branch

**Pull request merged**
